# Generated by Django 4.2.7 on 2025-08-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cart_cart_id_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='tax_rate',
            new_name='tax_price',
        ),
    ]
