# Generated by Django 4.2.7 on 2025-08-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_tax_rate_country_tax_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
