# Generated by Django 4.2.7 on 2025-08-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cartorderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='coupons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coupon'),
        ),
    ]
