# Generated by Django 4.2.7 on 2025-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cartorderitem_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='coupons',
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='api.coupon'),
        ),
    ]
